export const ICON_CATEGORY  = {
    COMMON_ICONS:'commonIcons',
    DOCUMENT_ICONS: 'documentIcons',
    FORM_ICONS: 'formIcons',
    GRID_ICONS: 'gridIcons',
    MODULE_ICONS: 'moduleIcons',
    PORTAL_ICON: 'portalIcons',
    WORK_ICON: 'workIcons',
    ACT_ENABLED_ICONS: 'actEnabledIcons',
    PAGING_ICONS: 'pagingIcons',
    STATE_ICONS: 'stateIcons',
    CASE_MANAGEMENT_ICONS: 'caseManagementIcons',
    ROUNDED_ICONS: 'roundedIcons',
    FOLDER_ICONS: 'folderIcons',
    COMMON_ICONS_32: 'commonIcons32',
    ERROR_ICON: 'errorIcon',
    COMMON_FORM_ARROWS: 'commonFormArrows',
    ENV_MGT: "envMgt",
    SPRITE_ICONS: "spriteIcons",
    DIALOG_ICONS: "dialogIcons",
};

export const ICONS = {
    //Common Icons
    HOME: { name: 'home', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    SIGN_OUT: { name: 'signOut', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    HELP: { name: 'help', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    ACCOUNT: { name: 'account', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    BACK: { name: 'back', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    SAVE: { name: 'save', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    COMMUNITY: { name: 'community', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    ASCENDING: { name: 'ascending', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    DESCENDING: { name: 'descending', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    NEW_TAB: { name: 'NewTab', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    AUTO_ARRANGE: { name: 'autoArrange', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    COPY: { name: 'copy', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    HELP_BLUE_OUTLINE: { name: 'helpBlueOutline', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    REFRESH: { name: 'refresh', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    DUPLICATE: { name: 'duplicate', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    OK: { name: 'ok', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    FILTER: { name: 'filter', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    ADD: { name: 'add', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    SUCCESS: { name: 'success', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    PRINT: { name: 'print', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    PDF: { name: 'pdf', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    PRINT_ERROR: { name: 'printError', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    PRINT_SUCCESS: { name: 'printSuccess', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    MINUS: { name: 'minus', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    PLUS: { name: 'plus', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    ERROR_OUTLINE: { name: 'errorOutline', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    ERROR: { name: 'error', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    SAVE_SUCCESS: { name: 'saveSuccess', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    PREVIOUS: { name: 'previous', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    NEXT: { name: 'next', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    UP: { name: 'up', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    LOADING: { name: 'loading', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    JOB_STATUS: { name: 'jobStatus', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    SEARCH_RESULT: { name: 'searchResult', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    INFO: { name: 'info', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    STATUS: { name: 'status', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    EDIT: { name: 'edit', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    PASTE: { name: 'paste', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    FILE_SEARCH: { name: 'fileSearch', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    IMPORTANT: { name: 'important', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    ZIP_RED: { name: 'zipRed', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    ZIP_BLACK: { name: 'zipBlack', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    DELETE_OUTLINE: { name: 'deleteOutline', iconCategory: ICON_CATEGORY.COMMON_ICONS},
    GRAPH: { name: 'graph', iconCategory: ICON_CATEGORY.COMMON_ICONS},

    //Common Form Arrows
    ARROWS_DOWN_DISABLED: { name: 'arrowsDownDisabled', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_DOWN_LIGHT: { name: 'arrowsDownLight', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_DOWN_DARK: { name: 'arrowsDownDark', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_UP_DISABLED: { name: 'arrowsUpDisabled', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_UP_LIGHT: { name: 'arrowsUpLight', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_UP_DARK: { name: 'arrowsUpDark', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_RIGHT_DISABLED: { name: 'arrowsRightDisabled', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_RIGHT_LIGHT: { name: 'arrowsRightLight', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_RIGHT_DARK: { name: 'arrowsRightDark', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_LEFT_DISABLED: { name: 'arrowsLeftDisabled', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_LEFT_LIGHT: { name: 'arrowsLeftLight', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},
    ARROWS_LEFT_DARK: { name: 'arrowsLeftDark', iconCategory: ICON_CATEGORY.COMMON_FORM_ARROWS},

    //Document Icons
    DOC_FILE_EDIT: { name: 'docFileEdit', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_REFRESH: { name: 'docRefresh', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_CONTENT_SEARCH: { name: 'docContentSearch', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_VIEW: { name: 'docView', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_SEARCH_ALL: { name: 'docSearchAll', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_ORDER: { name: 'docOrder', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_FILE: { name: 'docFile', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_SEARCH: { name: 'docSearch', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_EDIT: { name: 'docEdit', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_ADD: { name: 'docAdd', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_DELETE: { name: 'docDelete', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},
    DOC_COPY: { name: 'docCopy', iconCategory: ICON_CATEGORY.DOCUMENT_ICONS},

    //Form Icons
    FORM_TABLE: { name: 'formTable', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_NEXT: { name: 'formNext', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_PREVIOUS: { name: 'formPrevious', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_TIME: { name: 'formTime', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_UP: { name: 'formUp', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_DOWN: { name: 'formDown', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_UPWARD: { name: 'formUpward', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_DOWNWARD: { name: 'formDownward', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_DOWN_WHITE_BLURRED: { name: 'formDownWhiteBlurred', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_DOWN_WHITE: { name: 'formDownWhite', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_PREVIOUS_BLUE_BORDER: { name: 'formPreviousBlueBorder', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_NEXT_BLUE_BORDER: { name: 'formNextBlueBorder', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_REWIND: { name: 'formRewind', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_FAST_FORWARD: { name: 'formFastForward', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_NEXT_WHITE: { name: 'formNextWhite', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_PREVIOUS_WHITE: { name: 'formPreviousWhite', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_REWIND_WHITE: { name: 'formRewindWhite', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_FAST_FORWARD_WHITE: { name: 'formFastForwardWhite', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_ALERT: { name: 'formAlert', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_TEXT: { name: 'formText', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_TEXT_HASH: { name: 'formTextHash', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_LIST_ARROW: { name: 'formListArrow', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_CALENDER: { name: 'formCalender', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_CLOCK: { name: 'formClock', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_USER: { name: 'formUser', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_SCROLL: { name: 'formScroll', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_SCROLL_WITH_SLIDER: { name: 'formScrollWithSlider', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_PHONE: { name: 'formPhone', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_BLOCK: { name: 'formBlock', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_CHECKBOX: { name: 'formCheckbox', iconCategory: ICON_CATEGORY.FORM_ICONS},
    FORM_TRUE_FALSE: { name: 'formTrueFalse', iconCategory: ICON_CATEGORY.FORM_ICONS},

    //Grid Icons
    GRID_CLEAN: { name: 'gridClean', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_REMOVE: { name: 'gridRemove', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_ADD: { name: 'gridAdd', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_SAVE: { name: 'gridSave', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_DOWN: { name: 'gridDown', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_UP: { name: 'gridUp', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_RESET: { name: 'gridReset', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_SHOW: { name: 'gridShow', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_SETTING: { name: 'gridSetting', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_EDIT: { name: 'gridEdit', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_SORT: { name: 'gridSort', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_OK: { name: 'gridOk', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_CANCEL: { name: 'gridCancel', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_ADD_GREEN_OUTLINE: { name: 'gridAddGreenOutline', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_UP_OUTLINE: { name: 'gridUpOutline', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_DOWN_OUTLINE: { name: 'gridDownOutline', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_VIEW: { name: 'gridView', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_DUPLICATE: { name: 'gridDuplicate', iconCategory: ICON_CATEGORY.GRID_ICONS},
    GRID_SEARCH: { name: 'gridSearch', iconCategory: ICON_CATEGORY.GRID_ICONS},

    //Module Icons
    MODULE_WORK_SEARCH: { name: 'moduleWorkSearch', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_PREFERENCES: { name: 'modulePreferences', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_PLUS: { name: 'modulePlus', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_MINUS: { name: 'moduleMinus', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_FOLDER: { name: 'moduleFolder', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_FOLDER_OPEN: { name: 'moduleFolderOpen', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_FOLDER_OPEN_YELLOW: { name: 'moduleFolderOpenYellow', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_FOLDER_YELLOW: { name: 'moduleFolderYellow', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_SETTINGS: { name: 'moduleSettings', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_BAR_GRAPH: { name: 'moduleBarGraph', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_DOWN_ARROW: { name: 'moduleDownArrow', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_UP_ARROW: { name: 'moduleUpArrow', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_EDIT: { name: 'moduleEdit', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_SEARCH: { name: 'moduleSearch', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_MY_ULTERA: { name: 'moduleMyUltera', iconCategory: ICON_CATEGORY.MODULE_ICONS},
    MODULE_HISTORY_SEARCH: { name: 'moduleHistorySearch', iconCategory: ICON_CATEGORY.MODULE_ICONS},

    //Portal Icons
    PORTAL_SAVE: { name: 'portalSave', iconCategory: ICON_CATEGORY.PORTAL_ICON},
    PORTAL_DELETE: { name: 'portalDelete', iconCategory: ICON_CATEGORY.PORTAL_ICON},
    PORTAL_RENAME: { name: 'portalRename', iconCategory: ICON_CATEGORY.PORTAL_ICON},
    PORTAL_ORDER: { name: 'portalOrder', iconCategory: ICON_CATEGORY.PORTAL_ICON},
    PORTAL_ADD_WIDGET: { name: 'portalAddWidget', iconCategory: ICON_CATEGORY.PORTAL_ICON},
    PORTAL_SAVE_STAR: { name: 'portalSaveStar', iconCategory: ICON_CATEGORY.PORTAL_ICON},
    PORTAL_DELETE_WIDGET: { name: 'portalDeleteWidget', iconCategory: ICON_CATEGORY.PORTAL_ICON},
    PORTAL_EDIT_WIDGET: { name: 'portalEditWidget', iconCategory: ICON_CATEGORY.PORTAL_ICON},
    PORTAL_RESET: { name: 'portalReset', iconCategory: ICON_CATEGORY.PORTAL_ICON},

    //Work Icons
    WORK_RED_FLAG: { name: 'workRedFlag', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_GREEN_FLAG: { name: 'workGreenFlag', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_FORWARD: { name: 'workForward', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_LOCK: { name: 'workLock', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_PAUSE: { name: 'workPause', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_FILE: { name: 'workFile', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_FILE_CHECK: { name: 'workFileCheck', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_UNLOCK: { name: 'workUnlock', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_SAVE: { name: 'workSave', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_SEARCH: { name: 'workSearch', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_EDIT: { name: 'workEdit', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_ERROR: { name: 'workError', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_ADD_ATTACHMENT: { name: 'workAddAttachment', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_REMOVE_ATTACHMENT: { name: 'workRemoveAttachment', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_NOTE: { name: 'workNote', iconCategory: ICON_CATEGORY.WORK_ICON},
    WORK_VIEW_LOCKED: { name: 'workViewLocked', iconCategory: ICON_CATEGORY.WORK_ICON},

    //Common Act Enabled Icons
    COMMON_SAVE: { name: 'commonSave', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_PRINT: { name: 'commonPrint', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_CUT: { name: 'commonCut', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_PASTE: { name: 'commonPaste', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_ERASE: { name: 'commonErase', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_CLEAR: { name: 'commonClear', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_REFRESH: { name: 'commonRefresh', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_EDIT: { name: 'commonEdit', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_ADD_FILE: { name: 'commonAddFile', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_EDIT_FILE: { name: 'commonEditFile', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_EDIT_TABLE: { name: 'commonEditTable', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_NOTE: { name: 'commonNote', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_RIGHT_ARROWS: { name: 'commonRightArrows', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_TIME: { name: 'commonTime', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_TORCH: { name: 'commonTorch', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_VIEW: { name: 'commonView', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_BOOKMARK: { name: 'commonBookmark', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_BAR_GRAPH: { name: 'commonBarGraph', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_HUB: { name: 'commonHub', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_BOX: { name: 'commonBox', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_BOOKS: { name: 'commonBooks', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_MAIL: { name: 'commonMail', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_FILE: { name: 'commonFile', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_SETTINGS: { name: 'commonSettings', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_KEY: { name: 'commonKey', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_PACKAGE: { name: 'commonPackage', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_SHAPE: { name: 'commonShape', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_TABLE: { name: 'commonTable', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_COMMUNITY: { name: 'commonCommunity', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_FOLDER: { name: 'commonFolder', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_FOLDER_OPEN: { name: 'commonFolderOpen', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},
    COMMON_INFO: { name: 'commonInfo', iconCategory: ICON_CATEGORY.ACT_ENABLED_ICONS},

    //Paging Icons
    PAGING_PREVIOUS: { name: 'pagingPrevious', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_NEXT: { name: 'pagingNext', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_LAST: { name: 'pagingLast', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_FIRST: { name: 'pagingFirst', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_UP: { name: 'pagingUp', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_DISABLED_PREVIOUS: { name: 'pagingDisabledPrevious', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_DISABLED_NEXT: { name: 'pagingDisabledNext', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_DISABLED_LAST: { name: 'pagingDisabledLast', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_DISABLED_FIRST: { name: 'pagingDisabledFirst', iconCategory: ICON_CATEGORY.PAGING_ICONS},
    PAGING_DISABLED_UP: { name: 'pagingDisabledUp', iconCategory: ICON_CATEGORY.PAGING_ICONS},

    //State Icons
    STATE_LOADING: { name: 'stateLoading', iconCategory: ICON_CATEGORY.STATE_ICONS},
    STATE_LOADING_FAILED: { name: 'stateLoadingFailed', iconCategory: ICON_CATEGORY.STATE_ICONS},
    STATE_CANCEL: { name: 'stateCancel', iconCategory: ICON_CATEGORY.STATE_ICONS},
    STATE_OK: { name: 'stateOk', iconCategory: ICON_CATEGORY.STATE_ICONS},
    STATE_JOB_STATUS: { name: 'stateJobStatus', iconCategory: ICON_CATEGORY.STATE_ICONS},
    STATE_FAILED: { name: 'stateFailed', iconCategory: ICON_CATEGORY.STATE_ICONS},

    //Case Management
    CASE_CREATE_DIRECTORY: { name: 'caseCreateDirectory', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_DIRECTORY_ERROR: { name: 'caseDirectoryError', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_DIRECTORY_SEARCH: { name: 'caseDirectorySearch', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_EDIT: { name: 'caseEdit', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_VIEW: { name: 'caseView', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_PLAY: { name: 'casePlay', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_GRAY_CIRCLE: { name: 'caseGrayCircle', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_GRAY_ICON: { name: 'caseGrayIcon', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_FORWARD: { name: 'caseForward', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_FORWARD_NEXT_ARROW: { name: 'caseForwardNextArrow', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_OK: { name: 'caseOk', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_SEARCH: { name: 'caseSearch', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},
    CASE_FILE_OK: { name: 'caseFileOk', iconCategory: ICON_CATEGORY.CASE_MANAGEMENT_ICONS},

    //Rounded Icon
    ROUNDED_PREVIOUS: { name: 'roundedPrevious', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_DOWN: { name: 'roundedDown', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_NEXT: { name: 'roundedNext', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_UP: { name: 'roundedUp', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_CANCEL: { name: 'roundedCancel', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_DISABLED_PREVIOUS: { name: 'roundedDisabledPrevious', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_DISABLED_DOWN: { name: 'roundedDisabledDown', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_DISABLED_NEXT: { name: 'roundedDisabledNext', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_DISABLED_UP: { name: 'roundedDisabledUp', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},
    ROUNDED_DISABLED_CANCEL: { name: 'roundedDisabledCancel', iconCategory: ICON_CATEGORY.ROUNDED_ICONS},

    //Folder Icons
    FOLDER_CLOSED: { name: 'folderClosed', iconCategory: ICON_CATEGORY.FOLDER_ICONS},
    FOLDER_OPENED: { name: 'folderOpened', iconCategory: ICON_CATEGORY.FOLDER_ICONS},
    FOLDER_FILE: { name: 'folderFile', iconCategory: ICON_CATEGORY.FOLDER_ICONS},
    FOLDER_CREATE: { name: 'folderCreate', iconCategory: ICON_CATEGORY.FOLDER_ICONS},
    FOLDER_ERROR: { name: 'folderError', iconCategory: ICON_CATEGORY.FOLDER_ICONS},
    FOLDER_COPY: { name: 'folderCopy', iconCategory: ICON_CATEGORY.FOLDER_ICONS},

    //CommonIcon32
    COMMON_ALARM: { name: 'alarm', iconCategory: ICON_CATEGORY.COMMON_ICONS_32},
    COMMON_WARNING: { name: 'warning', iconCategory: ICON_CATEGORY.COMMON_ICONS_32},
    COMMON_FILE_VIEW: { name: 'fileView', iconCategory: ICON_CATEGORY.COMMON_ICONS_32},
    COMMON_SUCCESS: { name: 'success_Arrow', iconCategory: ICON_CATEGORY.COMMON_ICONS_32},
    COMMON_Module: { name: 'module', iconCategory: ICON_CATEGORY.COMMON_ICONS_32},

    //ERROR_ICON
    ERROR_ICON:{name: 'error', iconCategory:ICON_CATEGORY.ERROR_ICON},

    //Admin Env mgt
    ENV_SETTINGS: { name: 'envSettings', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_IMPORT: { name: 'envImport', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_EXPORT: { name: 'envExport', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_PROMOTE: { name: 'envPromote', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_DELETE: { name: 'envDelete', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_CREATE: { name: 'envCreate', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_TABLE: { name: 'envTable', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_DOWNLOAD_LIGHT: { name: 'envDownloadLight', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_LOG: { name: 'envLog', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_ACTIVE_JOB: { name: 'envActiveJob', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_ABORT: { name: 'envAbort', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_DOWNLOAD_DARK: { name: 'envDownloadDark', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_PROCEED: { name: 'envProceed', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_RIGHT_TICK: { name: 'envRightTick', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_AUDIT: { name: 'envAudit', iconCategory: ICON_CATEGORY.ENV_MGT},
    ENV_PROCEED_AUDIT: { name: 'envProceedAudit', iconCategory: ICON_CATEGORY.ENV_MGT},

    //Sprite Icons
    SPRITE_FILTER_ICON: { name: 'spriteFilterIcon', iconCategory: ICON_CATEGORY.SPRITE_ICONS},
    SPRITE_CLOSE_ICON: { name: 'spriteCloseIcon', iconCategory: ICON_CATEGORY.SPRITE_ICONS},
    SPRITE_CLOSE_HOVER_ICON: { name: 'spriteCloseHoverIcon', iconCategory: ICON_CATEGORY.SPRITE_ICONS},
    SPRITE_ADD_ICON:  { name: 'spriteAddIcon', iconCategory: ICON_CATEGORY.SPRITE_ICONS},
    SPRITE_RED_CLOSE_ICON:{name: 'spriteRedCloseIcon', iconCategory: ICON_CATEGORY.SPRITE_ICONS},
    //Dialog Icons
    WHITE_ALERT_ICON: {name: "whiteAlertIcon", iconCategory: ICON_CATEGORY.DIALOG_ICONS},
    VIOLET_ALERT_ICON: {name: "violetAlertIcon", iconCategory: ICON_CATEGORY.DIALOG_ICONS},
    RED_ALERT_ICON: {name: "redAlertIcon", iconCategory: ICON_CATEGORY.DIALOG_ICONS},
    QUESTION_MARK_ICON: {name: "questionMarkIcon", iconCategory: ICON_CATEGORY.DIALOG_ICONS},
    YELLOW_ALERT_ICON: {name: "yellowAlertIcon", iconCategory: ICON_CATEGORY.DIALOG_ICONS},
    CLOSE_ROUND_ICON: {name: "closeRoundIcon", iconCategory: ICON_CATEGORY.DIALOG_ICONS},
};