export const TABLE_HEADERS = {
    ipdWorkType:'Work Type',
    ipdWorkAssignment: 'Queue',
    ipdAssignedOwner: 'Assigned Owner',
    ipdStepName:'Step Name',
    CmAcmCaseIdentifier:'Case Identifier',
    IPD_ClaimNumber:'Claim #',
    IPD_ClaimType:'Claim Type',
    IPD_ClaimStatus:'Claim Status',
    IPD_ClaimRecvdDate: 'Claim Due Date',
    IPD_ClaimManager:'Claim Manager',
    IPD_FirstName:'First Name',
    IPD_LastName:'Last Name',
    IPD_DOB:'DOB',
    IPD_PhoneNumber :'Phone #',
    IPD_Covered:'Covered?',
    IPD_CoveredAmount:'Covered Amount',
    ipdResponse:'Response',
    ipdReason:'Reason',
    ipdRemark:'Remark',
    ipdHoldTime:'Hold Time',
    envId: "Identity",
    envName: "Name",
    description: "Description",
    lastModifiedUser: "Last User",
    lastModifiedDate: "Last Modified",
    jobName: "Job Name",
    startDate: "Start Date",
    status: "Status",
    enabled: "Enabled",
    numOfInstances: "# of Instances",
    environment:"Environment",
    workQueue: "Work Queue",
    process: "Process",
    adaptorTypeId: "Type"

};