export const spriteSheet = {
    'home': {
        x: 0,
        y: 0,
        width: 18,
        height: 18,
    },
    'signOut': {
        x: 0,
        y: 18,
        width: 18,
        height: 18,
    },
    'help': {
        x: 0,
        y: 36,
        width: 18,
        height: 18,
    },
    'account': {
        x: 0,
        y: 54,
        width: 18,
        height: 18,
    },
    'back': {
        x: 0,
        y: 80,
        width: 18,
        height: 18,
    },
    'save': {
        x: 0,
        y: 100,
        width: 18,
        height: 18,
    },
    'community': {
        x: 0,
        y: 128,
        width: 18,
        height: 18,
    },
    'ascending': {
        x: 0,
        y: 155,
        width: 18,
        height: 18,
    },
    'descending': {
        x: 0,
        y: 180,
        width: 18,
        height: 18,
    },
    'NewTab': {
        x: 0,
        y: 205,
        width: 18,
        height: 18,
    },
    'autoArrange': {
        x: 0,
        y: 232,
        width: 18,
        height: 18,
    },
    'copy': {
        x: 0,
        y: 265,
        width: 18,
        height: 18,
    },
    'helpBlueOutline': {
        x: 0,
        y: 295,
        width: 18,
        height: 18,
    },
    'refresh': {
        x: 0,
        y: 323,
        width: 18,
        height: 18,
    },
    'duplicate': {
        x: 0,
        y: 352,
        width: 18,
        height: 18,
    },
    'ok': {
        x: 0,
        y: 380,
        width: 18,
        height: 18,
    },
    'filter': {
        x: 0,
        y: 410,
        width: 18,
        height: 18,
    },
    'add': {
        x: 0,
        y: 438,
        width: 18,
        height: 18,
    },
    'success': {
        x: 0,
        y: 473,
        width: 18,
        height: 18,
    },
    'print': {
        x: 0,
        y: 503,
        width: 18,
        height: 18,
    },
    'pdf': {
        x: 0,
        y: 540,
        width: 18,
        height: 18,
    },
    'printError': {
        x: 0,
        y: 570,
        width: 18,
        height: 18,
    },
    'printSuccess': {
        x: 0,
        y: 595,
        width: 18,
        height: 18,
    },
    'minus': {
        x: 0,
        y: 623,
        width: 18,
        height: 18,
    },
    'plus': {
        x: 0,
        y: 645,
        width: 18,
        height: 18,
    },
    'errorOutline': {
        x: 0,
        y: 670,
        width: 18,
        height: 18,
    },
    'error': {
        x: 0,
        y: 698,
        width: 18,
        height: 18,
    },
    'saveSuccess': {
        x: 0,
        y: 730,
        width: 18,
        height: 18,
    },
    'previous': {
        x: 0,
        y: 760,
        width: 18,
        height: 18,
    },
    'next': {
        x: 0,
        y: 785,
        width: 18,
        height: 18,
    },
    'up': {
        x: 0,
        y: 815,
        width: 18,
        height: 18,
    },
    'loading': {
        x: 0,
        y: 850,
        width: 18,
        height: 18,
    },
    'jobStatus': {
        x: 0,
        y: 880,
        width: 18,
        height: 18,
    },
    'searchResult': {
        x: 0,
        y: 910,
        width: 18,
        height: 18,
    },
    'info': {
        x: 0,
        y: 940,
        width: 18,
        height: 18,
    },
    'status': {
        x: 0,
        y: 970,
        width: 18,
        height: 18,
    },
    'edit': {
        x: 0,
        y: 1000,
        width: 18,
        height: 18,
    },
    'paste': {
        x: 0,
        y: 1020,
        width: 18,
        height: 18,
    },
    'fileSearch': {
        x: 0,
        y: 1050,
        width: 18,
        height: 18,
    },
    'important': {
        x: 0,
        y: 1080,
        width: 18,
        height: 18,
    },
    'zipRed': {
        x: 0,
        y: 1100,
        width: 18,
        height: 18,
    },
    'zipBlack': {
        x: 0,
        y: 1120,
        width: 18,
        height: 18,
    },
    'deleteOutline': {
        x: 0,
        y: 1145,
        width: 18,
        height: 18,
    },
    'graph': {
        x: 0,
        y: 1170,
        width: 18,
        height: 18,
    },

    //Document Icons
    'docFileEdit': {
        x: 0,
        y: 0,
        width: 18,
        height: 18,
    },
    'docRefresh': {
        x: 0,
        y: 22,
        width: 18,
        height: 18,
    },
    'docContentSearch': {
        x: 0,
        y: 48,
        width: 18,
        height: 18,
    },
    'docView': {
        x: 0,
        y: 70,
        width: 18,
        height: 18,
    },
    'docSearchAll': {
        x: 0,
        y: 93,
        width: 18,
        height: 18,
    },
    'docOrder': {
        x: 0,
        y: 120,
        width: 18,
        height: 18,
    },
    'docFile': {
        x: 0,
        y: 150,
        width: 18,
        height: 18,
    },
    'docSearch': {
        x: 0,
        y: 180,
        width: 18,
        height: 18,
    },
    'docEdit': {
        x: 0,
        y: 210,
        width: 18,
        height: 18,
    },
    'docAdd': {
        x: 0,
        y: 235,
        width: 18,
        height: 18,
    },
    'docDelete': {
        x: 0,
        y: 258,
        width: 18,
        height: 18,
    },
    'docCopy': {
        x: 0,
        y: 280,
        width: 18,
        height: 18,
    },

    // Form Icons
    'formTable': {
        x: 0,
        y: 0,
        width: 18,
        height: 18,
    },
    'formNext': {
        x: 0,
        y: 18,
        width: 18,
        height: 18,
    },
    'formPrevious': {
        x: 0,
        y: 36,
        width: 18,
        height: 18,
    },
    'formTime': {
        x: 0,
        y: 60,
        width: 18,
        height: 18,
    },
    'formUp': {
        x: 0,
        y: 82,
        width: 18,
        height: 18,
    },
    'formDown': {
        x: 0,
        y: 100,
        width: 18,
        height: 18,
    },
    'formUpward': {
        x: 0,
        y: 118,
        width: 18,
        height: 18,
    },
    'formDownward': {
        x: 0,
        y: 139,
        width: 18,
        height: 18,
    },
    'formDownWhiteBlurred': {
        x: 0,
        y: 156,
        width: 18,
        height: 18,
    },
    'formDownWhite': {
        x: 0,
        y: 180,
        width: 18,
        height: 18,
    },
    'formPreviousBlueBorder': {
        x: 0,
        y: 200,
        width: 18,
        height: 18,
    },
    'formNextBlueBorder': {
        x: 0,
        y: 218,
        width: 18,
        height: 18,
    },
    'formRewind': {
        x: 0,
        y: 239,
        width: 18,
        height: 18,
    },
    'formFastForward': {
        x: 0,
        y: 269,
        width: 18,
        height: 18,
    },
    'formNextWhite': {
        x: 0,
        y: 300,
        width: 18,
        height: 18,
    },
    'formPreviousWhite': {
        x: 0,
        y: 328,
        width: 18,
        height: 18,
    },
    'formRewindWhite': {
        x: 0,
        y: 350,
        width: 18,
        height: 18,
    },
    'formFastForwardWhite': {
        x: 0,
        y: 375,
        width: 18,
        height: 18,
    },
    'formAlert': {
        x: 0,
        y: 410,
        width: 18,
        height: 18,
    },
    'formText': {
        x: 0,
        y: 438,
        width: 18,
        height: 18,
    },
    'formTextHash': {
        x: 0,
        y: 458,
        width: 18,
        height: 18,
    },
    'formListArrow': {
        x: 0,
        y: 478,
        width: 18,
        height: 18,
    },
    'formCalender': {
        x: 0,
        y: 500,
        width: 18,
        height: 18,
    },
    'formClock': {
        x: 0,
        y: 523,
        width: 18,
        height: 18,
    },
    'formUser': {
        x: 0,
        y: 540,
        width: 18,
        height: 18,
    },
    'formScroll': {
        x: 0,
        y: 565,
        width: 18,
        height: 18,
    },
    'formScrollWithSlider': {
        x: 0,
        y: 588,
        width: 18,
        height: 18,
    },
    'formPhone': {
        x: 0,
        y: 612,
        width: 18,
        height: 18,
    },
    'formBlock': {
        x: 0,
        y: 638,
        width: 18,
        height: 18,
    },
    'formCheckbox': {
        x: 0,
        y: 660,
        width: 18,
        height: 18,
    },
    'formTrueFalse': {
        x: 0,
        y: 685,
        width: 18,
        height: 18,
    },

// Grid Icons
    'gridClean': {
        x: 0,
        y: 0,
        width: 16,
        height: 18,
    },
    'gridAdd': {
        x: 0,
        y: 36,
        width: 16,
        height: 18,
    },
    'gridRemove': {
        x: 0,
        y: 18,
        width: 16,
        height: 18,
    },
    'gridSave': {
        x: 0,
        y: 55,
        width: 16,
        height: 18,
    },
    'gridDown': {
        x: 0,
        y: 70,
        width: 16,
        height: 14,
    },
    'gridUp': {
        x: 0,
        y: 80,
        width: 16,
        height: 14,
    },
    'gridReset': {
        x: 0,
        y: 93,
        width: 16,
        height: 18,
    },
    'gridShow': {
        x: 0,
        y: 112,
        width: 16,
        height: 18,
    },
    'gridSetting': {
        x: 0,
        y: 133,
        width: 16,
        height: 18,
    },
    'gridEdit': {
        x: 0,
        y: 198,
        width: 16,
        height: 18,
    },
    'gridSort': {
        x: 0,
        y: 225,
        width: 16,
        height: 18,
    },
    'gridOk': {
        x: 0,
        y: 265,
        width: 16,
        height: 18,
    },
    'gridCancel': {
        x: 0,
        y: 318,
        width: 16,
        height: 18,
    },
    'gridAddGreenOutline': {
        x: 0,
        y: 368,
        width: 16,
        height: 18,
    },
    'gridUpOutline': {
        x: 0,
        y: 400,
        width: 16,
        height: 18,
    },
    'gridDownOutline': {
        x: 0,
        y: 430,
        width: 16,
        height: 18,
    },
    'gridView': {
        x: 0,
        y: 465,
        width: 16,
        height: 18,
    },
    'gridDuplicate': {
        x: 0,
        y: 495,
        width: 16,
        height: 18,
    },
    'gridSearch': {
        x: 0,
        y: 518,
        width: 16,
        height: 18,
    },

    // Module Icons
    'moduleWorkSearch': {
        x: 0,
        y: 0,
        width: 18,
        height: 18,
    },
    'modulePreferences': {
        x: 0,
        y: 20,
        width: 18,
        height: 18,
    },
    'modulePlus': {
        x: 0,
        y: 36,
        width: 18,
        height: 18,
    },
    'moduleMinus': {
        x: 0,
        y: 55,
        width: 18,
        height: 14,
    },
    'moduleFolder': {
        x: 0,
        y: 68,
        width: 18,
        height: 18,
    },
    'moduleFolderOpen': {
        x: 0,
        y: 85,
        width: 18,
        height: 18,
    },
    'moduleFolderOpenYellow': {
        x: 0,
        y: 118,
        width: 18,
        height: 18,
    },
    'moduleFolderYellow': {
        x: 0,
        y: 134,
        width: 18,
        height: 18,
    },
    'moduleSettings': {
        x: 0,
        y: 152,
        width: 18,
        height: 18,
    },
    'moduleBarGraph': {
        x: 0,
        y: 170,
        width: 18,
        height: 18,
    },
    'moduleDownArrow': {
        x: 0,
        y: 195,
        width: 18,
        height: 18,
    },
    'moduleUpArrow': {
        x: 0,
        y: 210,
        width: 18,
        height: 18,
    },
    'moduleEdit': {
        x: 0,
        y: 230,
        width: 18,
        height: 18,
    },
    'moduleSearch': {
        x: 0,
        y: 256,
        width: 18,
        height: 18,
    },
    'moduleMyUltera': {
        x: 0,
        y: 278,
        width: 18,
        height: 18,
    },
    'moduleHistorySearch': {
        x: 0,
        y: 300,
        width: 18,
        height: 18,
    },

    //Portal Icons
    'portalSave': {
        x: 0,
        y: 0,
        width: 16,
        height: 18,
    },
    'portalDelete': {
        x: 0,
        y: 19,
        width: 16,
        height: 18,
    },
    'portalRename': {
        x: 0,
        y: 39,
        width: 16,
        height: 18,
    },
    'portalOrder': {
        x: 0,
        y: 59,
        width: 16,
        height: 18,
    },
    'portalAddWidget': {
        x: 0,
        y: 79,
        width: 16,
        height: 18,
    },
    'portalSaveStar': {
        x: 0,
        y: 99,
        width: 16,
        height: 18,
    },
    'portalDeleteWidget': {
        x: 0,
        y: 120,
        width: 16,
        height: 18,
    },
    'portalEditWidget': {
        x: 0,
        y: 140,
        width: 16,
        height: 18,
    },
    'portalReset': {
        x: 0,
        y: 160,
        width: 16,
        height: 18,
    },




    //Work Icons
    'workRedFlag': {
        x: 0,
        y: 0,
        width: 18,
        height: 18,
    },
    'workGreenFlag': {
        x: 0,
        y: 19,
        width: 18,
        height: 18,
    },
    'workForward': {
        x: 0,
        y: 37,
        width: 18,
        height: 18,
    },
    'workLock': {
        x: 0,
        y: 54,
        width: 18,
        height: 20,
    },
    'workPause': {
        x: 0,
        y: 76,
        width: 18,
        height: 18,
    },
    'workFile': {
        x: 0,
        y: 96,
        width: 18,
        height: 18,
    },
    'workFileCheck': {
        x: 0,
        y: 115,
        width: 18,
        height: 18,
    },
    'workUnlock': {
        x: 0,
        y: 133,
        width: 18,
        height: 18,
    },
    'workSave': {
        x: 0,
        y: 155,
        width: 18,
        height: 18,
    },
    'workSearch': {
        x: 0,
        y: 175,
        width: 18,
        height: 18,
    },
    'workEdit': {
        x: 0,
        y: 198,
        width: 18,
        height: 18,
    },
    'workError': {
        x: 0,
        y: 226,
        width: 18,
        height: 18,
    },
    'workAddAttachment': {
        x: 0,
        y: 254,
        width: 18,
        height: 18,
    },
    'workRemoveAttachment': {
        x: 0,
        y: 284,
        width: 18,
        height: 18,
    },
    'workNote': {
        x: 0,
        y: 316,
        width: 18,
        height: 18,
    },
    'workViewLocked': {
        x: 0,
        y: 350,
        width: 18,
        height: 18,
    },


    //Common Act Enabled Icons
    'commonSave': {
        x: 0,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonPrint': {
        x: 16,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonCut': {
        x: 32,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonPaste': {
        x: 48,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonErase': {
        x: 64,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonClear': {
        x: 80,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonRefresh': {
        x: 96,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonEdit': {
        x: 112,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonAddFile': {
        x: 128,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonEditFile': {
        x: 144,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonEditTable': {
        x: 160,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonNote': {
        x: 176,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonRightArrows': {
        x: 192,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonTime': {
        x: 208,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonTorch': {
        x: 224,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonView': {
        x: 240,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonBookmark': {
        x: 256,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonBarGraph': {
        x: 272,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonHub': {
        x: 288,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonBox': {
        x: 304,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonBooks': {
        x: 320,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonMail': {
        x: 336,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonFile': {
        x: 352,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonSettings': {
        x: 368,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonKey': {
        x: 384,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonPackage': {
        x: 400,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonShape': {
        x: 416,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonTable': {
        x: 432,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonCommunity': {
        x: 448,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonFolder': {
        x: 464,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonFolderOpen': {
        x: 480,
        y: 0,
        width: 16,
        height: 16,
    },
    'commonInfo': {
        x: 496,
        y: 0,
        width: 16,
        height: 16,
    },

    //Paging Icons
    'pagingPrevious': {
        x: 0,
        y: 0,
        width: 18,
        height: 18,
    },
    'pagingNext': {
        x: 18,
        y: 0,
        width: 18,
        height: 18,
    },
    'pagingLast': {
        x: 39,
        y: 0,
        width: 18,
        height: 18,
    },
    'pagingFirst': {
        x: 56,
        y: 0,
        width: 18,
        height: 18,
    },
    'pagingUp': {
        x: 78,
        y: 0,
        width: 18,
        height: 18,
    },
    'pagingDisabledPrevious': {
        x: 0,
        y: 20,
        width: 18,
        height: 18,
    },
    'pagingDisabledNext': {
        x: 18,
        y: 20,
        width: 18,
        height: 18,
    },
    'pagingDisabledLast': {
        x: 39,
        y: 20,
        width: 18,
        height: 18,
    },
    'pagingDisabledFirst': {
        x: 56,
        y: 20,
        width: 18,
        height: 18,
    },
    'pagingDisabledUp': {
        x: 78,
        y: 20,
        width: 18,
        height: 18,
    },

    //State Icons
    'stateLoading': {
        x: 0,
        y: 0,
        width: 18,
        height: 18,
    },
    'stateLoadingFailed': {
        x: 0,
        y: 20,
        width: 18,
        height: 18,
    },
    'stateCancel': {
        x: 0,
        y: 40,
        width: 18,
        height: 18,
    },
    'stateOk': {
        x: 0,
        y: 60,
        width: 18,
        height: 18,
    },
    'stateJobStatus': {
        x: 0,
        y: 80,
        width: 18,
        height: 18,
    },
    'stateFailed': {
        x: 0,
        y: 100,
        width: 18,
        height: 18,
    },

    //Case Management Icons
    'caseCreateDirectory': {
        x: 0,
        y: 0,
        width: 16,
        height: 12,
    },
    'caseDirectoryError': {
        x: 0,
        y: 20,
        width: 16,
        height: 18,
    },
    'caseDirectorySearch': {
        x: 0,
        y: 40,
        width: 16,
        height: 18,
    },
    'caseEdit': {
        x: 0,
        y: 60,
        width: 16,
        height: 18,
    },
    'caseView': {
        x: 0,
        y: 80,
        width: 16,
        height: 18,
    },
    'casePlay': {
        x: 0,
        y: 110,
        width: 16,
        height: 18,
    },
    'caseGrayCircle': {
        x: 0,
        y: 135,
        width: 16,
        height: 18,
    },
    'caseGrayIcon': {
        x: 0,
        y: 155,
        width: 16,
        height: 18,
    },
    'caseForward': {
        x: 0,
        y: 182,
        width: 16,
        height: 18,
    },
    'caseForwardNextArrow': {
        x: 0,
        y: 212,
        width: 16,
        height: 18,
    },
    'caseOk': {
        x: 0,
        y: 242,
        width: 16,
        height: 18,
    },
    'caseSearch': {
        x: 0,
        y: 272,
        width: 16,
        height: 18,
    },
    'caseFileOk': {
        x: 0,
        y: 300,
        width: 16,
        height: 18,
    },

    //Rounded Icons
    'roundedPrevious': {
        x: 0,
        y: 0,
        width: 16,
        height: 16,
    },
    'roundedDown': {
        x: 15,
        y: 0,
        width: 16,
        height: 16,
    },
    'roundedNext': {
        x: 30,
        y: 0,
        width: 16,
        height: 16,
    },
    'roundedUp': {
        x: 45,
        y: 0,
        width: 16,
        height: 16,
    },
    'roundedCancel': {
        x: 60,
        y: 0,
        width: 16,
        height: 16,
    },
    'roundedDisabledPrevious': {
        x: 0,
        y: 30,
        width: 16,
        height: 16,
    },
    'roundedDisabledDown': {
        x: 15,
        y: 30,
        width: 16,
        height: 16,
    },
    'roundedDisabledNext': {
        x: 30,
        y: 30,
        width: 16,
        height: 16,
    },
    'roundedDisabledUp': {
        x: 45,
        y: 30,
        width: 16,
        height: 16,
    },
    'roundedDisabledCancel': {
        x: 60,
        y: 30,
        width: 16,
        height: 16,
    },

    //Folder Icons
    'folderClosed': {
        x: 0,
        y: 0,
        width: 16,
        height: 16,
    },
    'folderOpened': {
        x: 16,
        y: 0,
        width: 16,
        height: 16,
    },
    'folderFile': {
        x: 32,
        y: 0,
        width: 16,
        height: 16,
    },
    'folderCreate': {
        x: 48,
        y: 0,
        width: 18,
        height: 16,
    },
    'folderError': {
        x: 66,
        y: 0,
        width: 18,
        height: 16,
    },
    'folderCopy': {
        x: 83,
        y: 0,
        width: 18,
        height: 16,
    },

    //Common icon 32
    'alarm': {
        x: 0,
        y: 0,
        width: 30,
        height: 30,
    },
    'warning': {
        x: 0,
        y: 50,
        width: 85,
        height: 30,
    },
    'fileView': {
        x: 0,
        y: 90,
        width: 30,
        height: 30,
    },
    'success_Arrow': {
        x: 0,
        y: 127,
        width: 30,
        height: 30,
    },
    'module': {
        x: 0,
        y: 168,
        width: 30,
        height: 30,
    },

    // Commons Form Arrows
    'arrowsDownDisabled':{
        x: 0,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsDownLight':{
        x: 35,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsDownDark':{
        x: 70,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsUpDisabled':{
        x: 105,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsUpLight':{
        x: 140,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsUpDark':{
        x: 175,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsRightDisabled':{
        x: 210,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsRightLight':{
        x: 245,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsRightDark':{
        x: 280,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsLeftDisabled':{
        x: 315,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsLeftLight':{
        x: 350,
        y: 0,
        width: 15,
        height: 10,
    },
    'arrowsLeftDark':{
        x: 385,
        y: 0,
        width: 15,
        height: 10,
    },

    // Admin Env mgt
    'envSettings':{
        x: 0,
        y: 0,
        width: 16,
        height: 18,
    },
    'envImport':{
        x: 0,
        y: 35,
        width: 16,
        height: 18,
    },
    'envExport':{
        x: 0,
        y: 65,
        width: 16,
        height: 18,
    },
    'envPromote':{
        x: 0,
        y: 93,
        width: 16,
        height: 18,
    },
    'envDelete':{
        x: 0,
        y: 125,
        width: 16,
        height: 18,
    },
    'envCreate':{
        x: 0,
        y: 155,
        width: 16,
        height: 18,
    },
    'envTable':{
        x: 0,
        y: 184,
        width: 16,
        height: 18,
    },
    'envDownloadLight':{
        x: 0,
        y: 215,
        width: 16,
        height: 18,
    },
    'envLog':{
        x: 0,
        y: 245,
        width: 16,
        height: 18,
    },
    'envActiveJob':{
        x: 0,
        y: 275,
        width: 16,
        height: 18,
    },
    'envAbort':{
        x: 0,
        y: 304,
        width: 16,
        height: 18,
    },
    'envDownloadDark':{
        x: 0,
        y: 334,
        width: 16,
        height: 18,
    },
    'envProceed':{
        x: 0,
        y: 365,
        width: 16,
        height: 18,
    },
    'envRightTick':{
        x: 0,
        y: 395,
        width: 16,
        height: 18,
    },
    'envAudit':{
        x: 0,
        y: 420,
        width: 16,
        height: 18,
    },
    'envProceedAudit':{
        x: 0,
        y: 445,
        width: 16,
        height: 18,
    },

    //sprite icons
    'spriteFilterIcon':{
        x: 100,
        y: 56,
        width: 16,
        height: 18,
    },
    'spriteCloseIcon':{
        x: 200,
        y: 56,
        width: 14,
        height: 18,
    },
    'spriteRedCloseIcon':{
        x: 200,
        y: 0,
        width: 18,
        height: 14,
    },
    'spriteCloseHoverIcon':{
        x: 180,
        y: 0,
        width: 14,
        height: 18,
    },
    'spriteAddIcon':{
        x: 220,
        y: 0,
        width: 14,
        height: 14,
    },

    //dialog icons
    'whiteAlertIcon':{
        x: 0,
        y: 0,
        width: 18,
        height: 18,
    },
    'violetAlertIcon':{
        x: 0,
        y: 19,
        width: 18,
        height: 18,
    },
    'redAlertIcon':{
        x: 0,
        y: 38,
        width: 18,
        height: 18,
    },
    'questionMarkIcon':{
        x: 0,
        y: 57,
        width: 18,
        height: 18,
    },
    'yellowAlertIcon':{
        x: 0,
        y: 76,
        width: 18,
        height: 18,
    },
    'closeRoundIcon':{
        x: 0,
        y: 95,
        width: 18,
        height: 18,
    }
};